# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Pursoo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Pursoo
  pod 'Firebase/Core'
  pod 'Fabric', '~> 1.7.6'
  pod 'Crashlytics', '~> 3.10.1'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'


  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'PursooTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
